### ISSUE TITLE
add support for enew tabs in :ZkNew

### ISSUE THREAD

**Issue by krlhBlupine** [Furkanzmc/zettelkasten.nvim#29]
Pretty much what it says on the tin- I'd like to be able to use the plugin to create new tabs when I make a new note, rather than horizontally splitting my existing buffer.

**Comment by Furkanzmc** [comment]
Hey!

Thanks for the issue.

I just pushed 8f733407446c89000a97fe157946b1823432a703 that changes `:ZkNew` so it accepts `|`.

You can now just use `tabnew | ZkNew | only` or any combination you prefer to change the way a new note is created.


![WindowsTerminal_kuqLOJGcJw](https://github.com/Furkanzmc/zettelkasten.nvim/assets/932717/11bf603d-74d4-433d-8b38-244d22e8f1bf)
