### ISSUE TITLE
:ZkBrowse returns error 'Table index is nil'

### ISSUE THREAD

**Issue by gutteringHearthplace** [Furkanzmc/zettelkasten.nvim#30]
![image](https://github.com/Furkanzmc/zettelkasten.nvim/assets/117933922/db9e9d38-080f-4771-9c6e-4049dcecb4b3)

Here's the stacktrace- sorry about the format, I couldn't figure out how to get the plaintext.

Here's the zettel section from my lazy.nvim config:
```
{'Furkanzmc/zettelkasten.nvim',
    name = 'zettelkasten',
    cmd = {'ZkNew', 'ZkBrowse'},
    config = function()
        require('zettelkasten').setup({
          id_format = '%Y%m%d%H%M',
          filename_pattern = '%d+',
          title_pattern = 'aliases: .+',
          notes_path = './',
      })
      end,
  }
```

I'm using AstroNvim, if that helps you at all. I've tried to doublecheck that this isn't a user error, I'm really unfamiliar with Lua regex, but there's definitely the possibility that I've just done something stupid.

**Comment by krlhBlupine** [comment]
It was user error, I had a permissions bug elsewhere in the OS.
