### ISSUE TITLE
Feature Request: add reference to a note

### ISSUE THREAD

**Issue by gkielian** [Furkanzmc/zettelkasten.nvim#7]
Enjoying the plugin! Trying to find a way to add the link to an existing note (tried looking in the .txt, wiki and help, might have missed it...)

thanks!

**Comment by Furkanzmc** [comment]
Thanks!

You can add a reference to an existing note by wrapping the file name in double angle brackets, e.g: `[[my existing note]]`. If you created a note using `:ZkNew`, then you can add a note by wrapping the note id in double angle brackets, e.g: `[[2022-02-27-06-05-03]]`. You can also use `:help i_CTRL-X_CTRL-U` to get a completion list of available notes to refer to.

I hope that answers the question.
